### ISSUE TITLE
Remove Venv folder from git tracking

### ISSUE THREAD

**Issue by ryaustin** [green-dino/Oberon#18]
To remove the virtual environment (`venv`) from your Git cache and properly add it to your `.gitignore` file, follow these steps:

1. **Update .gitignore**:
   - Open your `.gitignore` file.
   - Add the following line to ignore the `venv` directory:
     ```plaintext
     venv/
     ```

2. **Remove venv from Git cache**:
   - Open your terminal.
   - Navigate to your project directory.
   - Run the following command to remove the `venv` directory from Git cache:
     ```bash
     git rm -r --cached venv/
     ```
   - Commit the changes:
     ```bash
     git commit -m "Remove venv from git cache and add it to .gitignore"
     ```

3. **Verify**:
   - Run `git status` to ensure the `venv` directory is no longer tracked by Git.
   - Push the changes to your remote repository if necessary:
     ```bash
     git push
     ```

Following these steps will ensure that the `venv` directory is properly ignored by Git and removed from the repository's cache.

**Comment by green-dino** [comment]
Complete
